# Generated by Django 5.1.3 on 2025-05-20 04:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_apellido_user_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se registró el progreso')),
                ('completed', models.BooleanField(default=False, help_text='Si el ejercicio fue completado o no')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='users.workout')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='users.workoutexercise')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'workout_exercise', 'date')},
            },
        ),
    ]
