# Generated by Django 5.1.7 on 2025-05-22 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_apellido_user_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('sexo', models.CharField(max_length=10)),
                ('imc', models.FloatField()),
                ('porcentaje_grasa', models.FloatField()),
                ('actividad_fisica', models.CharField(max_length=100)),
                ('objetivo_principal', models.CharField(max_length=100)),
                ('tiempo_estimado', models.CharField(max_length=100)),
                ('sesiones_por_semana', models.PositiveIntegerField()),
                ('tiempo_por_sesion', models.CharField(max_length=50)),
                ('descansos', models.CharField(max_length=50)),
                ('experiencia', models.CharField(max_length=100)),
                ('nivel_fuerza', models.CharField(max_length=100)),
                ('nivel_resistencia', models.CharField(max_length=100)),
                ('flexibilidad', models.CharField(max_length=100)),
                ('lesion_trauma', models.CharField(max_length=100)),
                ('tipo_cuerpo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
