# Generated by Django 5.1.3 on 2025-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_workoutprogress_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogress',
            name='fatigue',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nivel de fatiga/dolor percibido de 1 (muy bajo) a 5 (muy alto)', null=True),
        ),
    ]
