# Generated by Django 5.1.7 on 2025-06-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_diagnostico'),
        ('users', '0006_workoutprogress_fatigue'),
    ]

    operations = [
    ]
