# Generated by Django 5.1.3 on 2025-06-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_0004_diagnostico_0006_workoutprogress_fatigue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('MEN', 'Mensual'), ('SEM', 'Semestral'), ('ANU', 'Anual')], max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('precio_cop', models.IntegerField()),
                ('duracion_meses', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
